-- Migration: 002_user_tables.sql
-- Description: Creates user authentication and personalisation tables
-- Requirements: 7.7, 9.3, 11.2, 13.7, 13.8, 14.7, 14.8
-- Depends on: 001_initial_schema.sql (projects table must exist for FK references)

-- ============================================================
-- Table: users
-- Stores registered user accounts.
-- Req 7.7: id is a UUID generated by gen_random_uuid()
-- ============================================================
CREATE TABLE users (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email               TEXT NOT NULL UNIQUE,
    password_hash       TEXT NOT NULL,              -- BCrypt hash, cost factor 12
    full_name           TEXT NOT NULL,
    mobile              TEXT,
    avatar_url          TEXT,
    is_verified         BOOLEAN DEFAULT FALSE,
    is_active           BOOLEAN DEFAULT TRUE,
    role                TEXT DEFAULT 'user',        -- 'user' | 'admin'
    email_verified_at   TIMESTAMPTZ,
    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users(email);


-- ============================================================
-- Table: refresh_tokens
-- Stores hashed refresh tokens for JWT session management.
-- Req 9.3: only SHA-256 hash of refresh token stored, not raw value
-- ============================================================
CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,               -- SHA-256 hash of the opaque token
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    device_info TEXT,                               -- browser / device hint
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user  ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token_hash);


-- ============================================================
-- Table: password_reset_tokens
-- Stores hashed one-time tokens for the forgot-password flow.
-- Req 11.2: SHA-256 hash stored; 1-hour expiry enforced at application level
-- ============================================================
CREATE TABLE password_reset_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,               -- SHA-256 hash of the raw reset token
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_password_reset_tokens_user  ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token_hash);


-- ============================================================
-- Table: email_verification_tokens
-- Stores hashed one-time tokens for the email verification flow.
-- ============================================================
CREATE TABLE email_verification_tokens (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,               -- SHA-256 hash of the raw verification token
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_email_verification_tokens_user  ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token_hash);


-- ============================================================
-- Table: saved_properties
-- Deliberate bookmarks a user places on projects for later review.
-- Req 13.7: UNIQUE constraint on (user_id, project_id) at DB level
-- Req 13.8: ON DELETE CASCADE from projects ensures cleanup on project deletion
-- ============================================================
CREATE TABLE saved_properties (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    notes       TEXT,                               -- optional user note
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, project_id)
);

CREATE INDEX idx_saved_props_user ON saved_properties(user_id);


-- ============================================================
-- Table: favorites
-- Quick heart-button favorites, separate from deliberate bookmarks.
-- Req 14.7: UNIQUE constraint on (user_id, project_id) at DB level
-- Req 14.8: ON DELETE CASCADE from projects ensures cleanup on project deletion
-- ============================================================
CREATE TABLE favorites (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, project_id)
);

CREATE INDEX idx_favorites_user ON favorites(user_id);


-- ============================================================
-- Table: saved_searches
-- Named, persisted search filter sets that users can re-run.
-- The filters column is JSONB supporting: pinCodes, district,
-- minFlats, maxFlats, projectStatus, sortBy (Req 15.8)
-- ============================================================
CREATE TABLE saved_searches (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,                     -- user-given label e.g. "3BHK in Kondapur"
    filters      JSONB NOT NULL,                    -- serialized filter state
    last_run_at  TIMESTAMPTZ,
    result_count INTEGER,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Example filters JSONB shape:
-- {
--   "pinCodes": ["500075"],
--   "district": "Rangareddy",
--   "minFlats": 100,
--   "maxFlats": 500,
--   "projectStatus": "Ongoing",
--   "sortBy": "bookingPercent"
-- }

CREATE INDEX idx_saved_searches_user    ON saved_searches(user_id);
CREATE INDEX idx_saved_searches_filters ON saved_searches USING GIN(filters);


-- ============================================================
-- Table: comparison_results
-- Persisted side-by-side project comparisons.
-- project_ids is a TEXT array referencing project IDs.
-- snapshot captures comparison data at save time (optional JSONB).
-- ============================================================
CREATE TABLE comparison_results (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT,                               -- optional user-given label
    project_ids TEXT[] NOT NULL,                    -- array of project ids being compared
    snapshot    JSONB,                              -- optional: snapshot of comparison data at save time
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_comparisons_user ON comparison_results(user_id);
